Watching for file changes with StatReloader
Crew list view called
10 SpaceCats in the crew
Crew list view called
20 SpaceCats in the crew
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/kristoffer/Documents/Conferences/EuroSTAR 2024/spacecats/apps/missions/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/kristoffer/Documents/Conferences/EuroSTAR 2024/spacecats/apps/missions/migrations/0002_migrate_spacecat_data.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/kristoffer/Documents/Conferences/EuroSTAR 2024/spacecats/apps/missions/migrations/0003_delete_spacecat_alter_mission_spacecats.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /favicon.ico
Watching for file changes with StatReloader
Internal Server Error: /admin/spacecats/spacecat/
Traceback (most recent call last):
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: spacecats_spacecat

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/contrib/admin/views/main.py", line 123, in __init__
    self.get_results(request)
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/contrib/admin/views/main.py", line 279, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/core/paginator.py", line 93, in count
    return c()
           ^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/db/models/sql/query.py", line 568, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/db/models/sql/query.py", line 554, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kristoffer/.cache/pypoetry/virtualenvs/eurostar_2024-2ySr1xSG-py3.11/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: spacecats_spacecat
Watching for file changes with StatReloader
Watching for file changes with StatReloader
